config/routes.rb
Napster::Application.routes.draw do
  resources :friendships

  resources :fortunes
  resources :users, :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/about' => 'fortunes#about'
  match '/auth/facebook/callback' => 'user_sessions#createfb'
  match '/auth/github/callback' => 'user_sessions#creategh'
  match '/auth/logout' => 'user_sessions#destroysocial'
  match '/nie_pamietam_hasla' => 'user_sessions_#nie_pamietam_hasla'
  match '/przypomnienie_hasla' => 'user_sessions#przypomnienie'
  match '/reset_hasla' => 'user_sessions_#reset_hasla'
  match '/nowe_haslo' => 'users#nowe_haslo'

root :to => 'fortunes#witaj'
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
  tracked
def self.search(search, page)
  paginate :per_page => 10, :page => page,
           :conditions => ['wykonawca like :q or tytul like :q or album like :q or user_username like :q', q: "%#{search}%"], :order => 'wykonawca'
end
  validates :wykonawca, length: { in: 2..30 }, allow_blank: false
  validates :tytul, length: { in: 2..40 }, allow_blank: false
  validates :album, length: { maximum: 35 }, allow_blank: true
  validates :tekst, length: { maximum: 5000 }, allow_blank: true
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  # GET /fortunes.json
  
  helper_method :sort_column, :sort_direction
  def index
    @fortunes = Fortune.order(sort_column + " " + sort_direction).page(params[:page]).per_page(10).search(params[:search], params[:page])
    @activities = PublicActivity::Activity.last(5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
 def create
    @fortune = Fortune.new(params[:fortune])
    if current_user
    @fortune.user_username = current_user.username
    else
    @fortune.user_username = current_usersocial[:name]
    end

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Piosenka pozytywnie stworzona' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Piosenka pozytywnie zaktualizowana.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    if current_user
	if current_user.username == @fortune.user_username
    	@fortune.destroy
	end
    else current_usersocial
	if current_usersocial[:name] == @fortune.user_username
	@fortune.destroy
	end
    end
	

    respond_to do |format|
      format.html { redirect_to fortunes_url, notice: 'Piosenka usunieta.' }
      format.json { head :no_content }
    end
  end
  private
  
  def sort_column
    Fortune.column_names.include?(params[:sort]) ? params[:sort] : "wykonawca"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/views/fortunes/_form.html.erb
  <%= f.error_notification %>

  <div class="fortune-inputs">
    <%= f.input :wykonawca %>
    <%= f.input :tytul %>
    <%= f.input :album %>
    <%= f.input :tekst, :cols => "30", :rows => "10" %>
  </div>

app/views/fortunes/about.html.erb
<font style="bold" size="5" color="#100000">Członkowie Grupy:</font><br><br>
<font style="bold" size="4" color="#100000"><center>Miłosz Osiński<br><br>Marcin Magierski<br><br>Michał Grochalski<br><br>Krystian Hallmann<br><br>Sebastian Mikołajczyk<br><br></center></font>
<div class="fb-like-box" data-href="http://www.facebook.com/pages/Napster/163156913809271" data-width="292" data-height="460" data-show-faces="true" data-border="0" data-frameborder="0" data-stream="false" data-header="false"></div>
<div class="zalozenia">
<font style="bold" size="5" color="#100000">Założenia Projektu:</font><br><br>
<font style="bold" size="4" color="#100000">Stworzenie serwisu w którym użytkownik może dodać piosenke czyli wykonawce<br>tytuł album i tekst podzielić się nią na facebook-u lub twitterze.<br>Umożliwienie użytkownikowi utworzenia konta z własnym avatarem.<br>
Posiadanie listy znajomych z serwisu.</font>
</div>
<a id="forkme_banner" href="https://github.com/mosinski/napster">Fork Me on GitHub</a>

app/views/fortunes/edit.html.erb
<% title "Edycja Piosenki" %>
<h1><%= yield(:title) %></h1>
<% if current_user %>
<% if current_user.username == @fortune.user_username %>

<%= simple_form_for(@fortune) do |f| %>
<%= render partial: 'form', locals: { f: f } %>
  <%= f.button :submit, :class => 'btn btn-success', :value =>"Aktualizuj Piosenke" %> <%= link_to 'Powrót', fortunes_path, :class => 'btn btn-warning'%>
    <div class="teledysk">
      <%= f.input :videoclip, :placeholder => 'URL Teledysku' %>
      <%= f.input :cover, :placeholder => 'URL Okładki Albumu' %>
    </div>
<% end %>

<% else %>
<center><%= image_tag("dostep_zabroniony.gif") %></center><br/>
<% end %>
<% else %>
<center><%= image_tag("dostep_zabroniony.gif") %></center><br/>
<% end %>

app/views/fortunes/index.html.erb
<% title "Piosenki" %>
<h1><%= yield(:title) %></h1>
<style>
#lewo {border-left:0; color:#000000;font-family: 'Exo', sans-serif;font-size:15px;}
#lewy {border-left:0;}
#wyk  {text-align:right;}
#wyko {text-align:right; color:#000000;font-family: 'Exo', sans-serif;font-size:15px;}
#gora {font-family: 'Audiowide', cursive; font-size:14px;}
#activity_info{
margin-left:100px;
bottom:5pt;
right:4pt;
z-index:3;
display:block;
position:fixed;
color:white;
}
.wyszukiwarka{
margin-top:-50px;
margin-left:-100px;
}
</style>
<div class="wyszukiwarka">
<%= form_tag request.path, :method => 'get' do %>
  <%= text_field_tag  :search, params[:search], :placeholder => 'Wyszukaj:   Wykonawce Tytuł Album' %>
<% end %>
</div>	
<table style="border:0" class="table">
  <thead id="gora">
    <th id="wyk"><%= sortable "wykonawca" %></th>
    <th id="lewy"><%= sortable "tytul", "Tytuł" %></th>
    <th id="lewy"><%= sortable "album" %></th>
    <th id="lewy">Tekst</th>
    <th id="lewy"></th>
    <th id="lewy"></th>
    <th id="lewy"></th>
  </thead>

<% @fortunes.each do |fortune| %>
  <tr style="border-middle:0">
    <td id="wyko"><%= fortune.wykonawca %></td>
    <td id="lewo"><%= fortune.tytul %></td>
    <td id="lewo"><%= fortune.album %></td>
    <td id="lewo"><% if fortune.tekst == '' %><img src="http://www.lingeo.pl/tabela/images/no.png" alt="Brak Tekstu">
    <% elsif fortune.tekst.include? "ą" or fortune.tekst.include? "ę" or fortune.tekst.include? "ł" or fortune.tekst.include? "ć" %>
    <%= image_tag("flag_pl.png") %>
    <% elsif fortune.tekst.include? "'s" or fortune.tekst.include? " is " or fortune.tekst.include? "you"  %>
    <%= image_tag("flag_gb.png") %>
    <% elsif fortune.tekst.include? "ä" or fortune.tekst.include? "ö" or fortune.tekst.include? "ü"  %>
    <%= image_tag("flag_de.png") %>
    <% else %><img src="https://biolincc.nhlbi.nih.gov/static/img/icons/question_mark.png" alt="?" style="margin-left:15px"><% end %></td>
    <td id="lewo"><%= link_to 'Pokaż', fortune, :class => 'btn btn-mini btn-inverse' %></td>
    <% if current_user %>
    <% if fortune.user_username == current_user.username %>
    <td id="lewo"><%= link_to 'Edytuj', edit_fortune_path(fortune), :class => 'btn btn-mini' %></td>
    <td id="lewo"><%= link_to 'Usuń', fortune, confirm: 'Czy napewno chcesz usunąć?', method: :delete, :class => 'btn btn-mini btn-danger' %></td>
    <% end %>
    <% elsif current_usersocial %>
    <% if fortune.user_username == current_usersocial[:name] %>
    <td id="lewo"><%= link_to 'Edytuj', edit_fortune_path(fortune), :class => 'btn btn-mini' %></td>
    <td id="lewo"><%= link_to 'Usuń', fortune, confirm: 'Czy napewno chcesz usunąć?', method: :delete, :class => 'btn btn-mini btn-danger' %></td>
    <% end %>
<% end %>
</tr>
<% end %>
</table>
<div class="page_info" align="center">
  <%= page_entries_info @fortunes %>
</div>
<div class="pager" align="right">
  <%= will_paginate @fortunes, :container => false %>
</div>
<% if current_user %>
<%= link_to 'Dodaj Piosenke', new_fortune_path, :class => 'btn btn-primary' %>
<% end %>
<div id="activity_info">
<h3 id="show"><center>Aktywności<%= image_tag("icon-show.gif") %></center></h3>
<div id="activity_show">
<% for activity in @activities %>
  <% if activity.text == 'create' %><%= image_tag("add.png") %>Dodano Piosenkę!<br/>
  <% elsif activity.text == 'update' %><%= image_tag("update.png") %>Edytow. Piosenkę.<br/>
  <% elsif activity.text == 'delete' %><%= image_tag("delete.png") %>Usunięto Piosenkę.<br/>
   <% end %>
    <% end %>
</div>
</div>

app/views/fortunes/new.html.erb
<% title "Nowa Piosenka" %>
<h1><%= yield(:title) %></h1>
<%= simple_form_for(@fortune) do |f| %>
<%= render partial: 'form', locals: { f: f } %>
  <%= f.button :submit, :class => 'btn btn-success', :value =>"Dodaj Piosenke" %> <%= link_to 'Powrót', fortunes_path, :class => 'btn btn-warning'%>
    <div class="teledysk">
      <%= f.input :videoclip, :placeholder => 'URL Teledysku' %>
      <%= f.input :cover, :placeholder => 'URL Okładki Albumu' %>
    </div>
<% end %>

app/views/fortunes/show.html.erb
<script src="http://napsterug.herokuapp.com/tooltip.js"></script>
<script src="http://napsterug.herokuapp.com/popover.js"></script>
<% if (@fortune.videoclip != "") && (@fortune.videoclip.include? "www.youtube.com/watch?v=") %>
	<% if @fortune.videoclip.match(/^https?:\/\//) %>
	<% else %>
	<% @fortune.videoclip = "http://#{@fortune.videoclip}" %>
	<% end %>
		<% if @fortune.videoclip.match(/\=0$/) %>
		<% else %>
		<% @fortune.videoclip = "#{@fortune.videoclip}?rel=0" %>
		<% end %>
<% @fortune.videoclip["watch?v="]= "embed/" %>
<% @fortune.save %>
<% end %>

<% title @fortune.wykonawca + " - " + @fortune.tytul %>

<p id="notice">&nbsp;Piosenka utworzona: <%= @fortune.created_at.strftime("%d-%m-%Y") %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<BIG><font color="0066FF"><%= notice %></font></BIG><br>Ostatnia modyfikacja: <%= @fortune.updated_at.strftime("%d-%m-%Y") %>
<font style="margin-left:48%;">Piosenkę dodał:</font>
<% if User.find_all_by_username(@fortune.user_username) == 0 %>
<font style="font-size:15px;color:green;"><%= link_to (@fortune.user_username), @user = User.find_all_by_username(@fortune.user_username), :class => "notice_link", :rel => "popover", "data-original-title" => @fortune.user_username, "data-placement" => "right", "data-html" => "true", "data-content" => "Dodał "+Fortune.find_all_by_user_username(@fortune.user_username).count.to_s+" piosenek<br>Ma "+ Friendship.find_all_by_friend_id(User.find_all_by_username(@fortune.user_username)).count.to_s+" znajomych" %></font>
<% else %>
<font style="font-size:15px;color:green;"><%= link_to (@fortune.user_username), '', :class => "notice_link", :rel => "popover", "data-original-title" => @fortune.user_username, "data-placement" => "right", "data-html" => "true", "data-content" => "Dodał "+Fortune.find_all_by_user_username(@fortune.user_username).count.to_s+" piosenek<br>Ma "+ Friendship.find_all_by_friend_id(User.find_all_by_username(@fortune.user_username)).count.to_s+" znajomych" %></font>
<% end %>
</p>

<p>
  <h1><%= @fortune.wykonawca %> - <%= @fortune.tytul %></h1><center><div class='spread'><div class='twshare left'><a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="funonrails">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script><div class="fb_button" style="background:none;position: relative; top: -3px;"><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" layout="button_count" show_faces="false" width="45" font=""></fb:like></div></center>
</p>
<div class="teledysk_show">
<% if @fortune.videoclip != ''%>
<iframe title="Video intro" <%= video_tag(@fortune.videoclip, :size => "350x197",:poster => "http://www.oculu.com/wp-content/uploads/2011/04/20110421231855napster_spotlight.jpg") %> frameborder="0" > </iframe>
<% else %>
<%= image_tag("napster_video.jpg", :size => "350x197") %>
<% end %>
</div>
<div class="cover_show">
<% if @fortune.cover != ''%>
<%= image_tag("napster_cover.png", :size => "330x288") %>
<%= image_tag(@fortune.cover, :class => "okladka", :size => "275x269") %>
<% end %>
</div>
<div class="tekst_show">
  <font style="font-family: 'Audiowide', cursive; font-size:14px;"><center><b>Tekst:</b></center></font><br>
  <font style="font-family: 'Exo', sans-serif; font-size:15px; color:black;"><center><%=simple_format h @fortune.tekst %></center></font>
</div>

<% if current_user %>
<%= link_to 'Edytuj', edit_fortune_path(@fortune), :class => 'btn btn-success' %><% end %> <%= link_to 'Powrót', fortunes_path, :class => 'btn btn-warning' %>

app/views/fortunes/witaj.html.erb
<script src="http://napsterug.herokuapp.com/pwdstr.js"></script>
<%= render :partial => "users/rejestracja" %>
<iframe height="400" width="800" src="/slajdy" SCROLLING="no" frameborder="0"></iframe>
<div class="witaj_info">
<h2>Wystarczy się zarejestrować i zalogować. Zapraszamy!</h2><br>
<span class="label label-info">NOWOŚĆ</span><h3>Przeglądanie Portalu jako Gość <%= link_to 'Wchodzę!', fortunes_path, :class => 'btn btn-warning'%></h3>
</div>
<img src="http://napsterug.herokuapp.com/Girl.png" alt="Girl" class="girl">
<img src="http://napsterug.herokuapp.com/Boy.gif" alt="Boy" class="boy">