config/routes.rb
Napster::Application.routes.draw do
  resources :friendships

  resources :fortunes
  resources :users, :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/about' => 'fortunes#about'
  match '/auth/facebook/callback' => 'user_sessions#createfb'
  match '/auth/github/callback' => 'user_sessions#creategh'
  match '/auth/logout' => 'user_sessions#destroysocial'
  match '/nie_pamietam_hasla' => 'user_sessions_#nie_pamietam_hasla'
  match '/przypomnienie_hasla' => 'user_sessions#przypomnienie'
  match '/reset_hasla' => 'user_sessions_#reset_hasla'
  match '/nowe_haslo' => 'users#nowe_haslo'

root :to => 'fortunes#witaj'
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])
    
    respond_to do |format|
      if @user_session.save 
        format.html { redirect_to(:fortunes, :notice => 'Zalogowany!') }
        format.xml { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(:root, :notice => 'Wylogowany!') }
      format.xml { head :ok }
    end
  end

  def createfb
    session[:current_user] = {:image => request.env['omniauth.auth'][:info][:image],:name => request.env['omniauth.auth'][:info][:name]}
    redirect_to (:fortunes), :notice => "Zalogowany przez Facebook'a!"
  end

  def creategh
    session[:current_user] = {:image => request.env['omniauth.auth'][:info][:image],:name => request.env['omniauth.auth'][:info][:name]}
    redirect_to (:fortunes), :notice => "Zalogowany przez Github!"
  end

  def destroysocial
    session.delete(:current_user)
    redirect_to root_path, :notice => "Wylogowany!"
  end
  
  def przypomnienie
    @user = User.find_by_username(params[:login_input])
    if @user != NIL
    @user.kod_dostepu = SecureRandom.hex(10)
    @user.save
    PasswordResetMailer.password_reset_sender(@user).deliver

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Dostarczono mail!' }
      format.json { head :no_content }
    end
    else
    redirect_to root_url, notice: 'Login nieznany!'
   end
  end


end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= simple_form_for(@user_session) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :password %>
  </div>

<%= f.check_box :remember_me %><%= f.label :zapamietaj_mnie %>
<br /><br /><br /><br />

    <%= f.button :submit, :class => 'btn btn-success', :value => 'Zaloguj się'%> <%= link_to 'Powrót', root_url,:class => 'btn btn-warning' %>
<% end %>

app/views/user_sessions/_logowanie.erb
<%= form_for(@user_session || UserSession.new) do |f| %>

  <div class="logowanie_domowa">
    <%= f.text_field :username, :class => 'logowanie', :placeholder => 'Nazwa Konta' %>
    <%= f.password_field :password, :class => 'logowanie', :placeholder => 'Hasło' %>
    <%= f.check_box :remember_me, :title => 'Zapamiętaj Mnie', :id => 'zapamietaj_mnie' %>
    <%= f.button :Zaloguj, :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<% title "Logowanie" %>
<h1><%= yield(:title) %></h1>
<br>
<%= render 'form' %>
<%= link_to 'Zapomniałem hasła » ', '/nie_pamietam_hasla' %> | <%= link_to 'Nie mam konta » ', new_user_path %>

app/views/user_sessions/nie_pamietam_hasla.html.erb
<% title "Przypomnienie Hasła" %>
<h1><%= yield(:title) %></h1>
<br><br>
<%= form_tag "/przypomnienie_hasla" do %>
  <b><%= label_tag(:q, "Nick Profilu: ", :class => "label_przypomnienie") %></b>
  <%= text_field_tag(:login_input, nil, :placeholder => "Wpisz swój login z serwisu") %><br><br>

<div style="visibility: visible; left: 700px; top: 135px; opacity: 1;" class="jfk-bubble">
<div class="jfk-bubble-content-id">
<ul id="signupidvusage-bubble-content" class="secondary" style="margin: 0px 18px 0px 18px;">

  <b>Przypomnienie Hasła</b>, <br>
  Po wpisaniu <u>poprawnego</u> loginu konta z naszego serwisu<br>
  na mail podany przy rejestracji zostanie wysłana wiadomość<br>
  z dalszymi instrukcjami.

  </ul>
</div>
</div>

  <%= submit_tag " Wyślij ", :class => 'btn btn-success', :id => "wyslij_przypomnienie" %>

<% end %>

app/views/user_sessions/reset_hasla.html.erb
<% title "Reset Hasła" %>
<h1><%= yield(:title) %></h1>
<br><br>
<%= form_tag "/nowe_haslo" do %>
 <div class="field">
 <b><%= label_tag(:q, "Kod dostępu: ", :class => "label_przypomnienie") %></b>
    <%= text_field_tag :kod_dostepu_reset %>
  </div>
 <div class="field">
 <b><%= label_tag(:q, "Nowe Hasło: ", :class => "label_przypomnienie") %></b>
    <%= password_field_tag :password %>
    <div class="password_test"><span id="password_time"></span></div>
  </div>
 <div class="field">
 <b><%= label_tag(:q, "Powtórz Nowe Hasło: ", :class => "label_przypomnienie") %></b>
      <%= password_field_tag :password_confirmation %>
  </div>
<div style="visibility: visible; left: 700px; top: 135px; opacity: 1;" class="jfk-bubble">
<div class="jfk-bubble-content-id">
<ul id="signupidvusage-bubble-content" class="secondary" style="margin: 0px 18px 0px 18px;">

  <b>Reset Hasła</b>, <br>
  Proszę wpisać <u>kod dostępu</u> podany w mailu<br>
  Wypełnić pola: Nowe Hasło i Powtórz Nowe Hasło<br>
  Potwierdź a twoje hasło zostanie zmienione.<br><br>
  Nie znasz kodu dostępu? Przejdź <b><a href="/nie_pamietam_hasla">Tutaj</a></b>

  </ul>
</div>
</div>
 <%= submit_tag "Potwierdzam", :class => 'btn btn-success', :id => "wyslij_przypomnienie" %>
<% end %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>