config/routes.rb
Napster::Application.routes.draw do
  resources :friendships

  resources :fortunes
  resources :users, :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/about' => 'fortunes#about'
  match '/auth/facebook/callback' => 'user_sessions#createfb'
  match '/auth/github/callback' => 'user_sessions#creategh'
  match '/auth/logout' => 'user_sessions#destroysocial'
  match '/nie_pamietam_hasla' => 'user_sessions_#nie_pamietam_hasla'
  match '/przypomnienie_hasla' => 'user_sessions#przypomnienie'
  match '/reset_hasla' => 'user_sessions_#reset_hasla'
  match '/nowe_haslo' => 'users#nowe_haslo'

root :to => 'fortunes#witaj'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link rel="Shortcut icon" href="http://napsterug.herokuapp.com/favicon.ico" />
<head>
  <title>Napster - <%= yield(:title) %><% if yield(:title) == '' %>Twoja Biblioteka Piosenek<% end %></title>
  <!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Exo:500' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Emblema+One' rel='stylesheet' type='text/css'>
  <script src="https://raw.github.com/mosinski/mosinski.pl/master/x10%20masonry%20transparent_pliki/js/three.js" id="canvas"></script>
  <script src="https://raw.github.com/mosinski/mosinski.pl/master/x10%20masonry%20transparent_pliki/js/Bird.js" id="canvas"></script>
  <script src="https://raw.github.com/mosinski/mosinski.pl/master/x10%20masonry%20transparent_pliki/js/stats.js" id="canvas"></script>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <img src="http://napsterug.herokuapp.com/logo.png" alt="napsterlogo" align="left">
      <ul class="nav">
        <% if current_user or current_usersocial %>
	<li><a href="/fortunes">Strona Główna</a></li>
	<% else %>
        <li><a href="/">Strona Główna</a></li>
	<% end %>
        <li><a href="/about.html">O nas</a></li>
      </ul>
      <ul class="nav pull-right">
	<li><font color="yellow" size="2px"><%= notice %></font></li>
	<% if current_user %>
        <% if (current_user.avatarurl.nil?) or (current_user.avatarurl == '') %>
	<li id="nav_avatar"><%= image_tag avatar_url(current_user),:width => 50, :height => 50 %></li>
        <% else %>
        <li id="nav_avatar"><%= image_tag(current_user.avatarurl, :class => "avatar", :size => "50x50") %></li>
        <% end %>
	<li id="nav_nazwa_konta"><%= current_user.username %></li>
        <li><%= link_to "Profil", edit_user_path(current_user.id)%></li>
        <li><%= link_to "Wyloguj", :logout%></li>
        <% elsif current_usersocial %>
	<li id="nav_avatar"><%= image_tag(current_usersocial[:image], :class => "avatar", :size => "50x50") %></li>
	<li id="nav_nazwa_konta"><%= current_usersocial[:name] %></li>
	<li><%= link_to 'Wyloguj','/auth/logout' %></li>
	<% else %>
	<li id="nav_icony"><%= link_to image_tag('gh_icon.png', :title => 'Zaloguj przez Github'),'/auth/github' %></li>
	<li id="nav_icony"><%= link_to image_tag('fb_icon.png', :title => 'Zaloguj przez Facebook'),'/auth/facebook' %></li>
        <li><%= render :partial => "user_sessions/logowanie" %></li>
        <li><%= link_to "Rejestracja", new_user_path%></li>
        <% end %>
</div>
    </div>
  </div>
</div>
<% if current_user or current_usersocial %>
<div class="pasek_boczny">
<p>
<strong class="ukryj"><%= image_tag("hide.png") %></strong>
<strong class="pokaz"><%= image_tag("hideMirror.png") %></strong>
</p>
<table class="menu_person" align="center" width="100" cellspacing="2" cellpadding="2" style="height:100px; border:0">
<thead></thead>
<tbody>
<tr><td style="border:0"><%= link_to image_tag("new.png"), new_fortune_path %></td></tr>
<tr style="border:0"><td style="border:0"><%= link_to image_tag("music.png"), fortunes_path %></td></tr>
<tr><td style="border:0"><%= link_to image_tag("users.png"), users_path %></td></tr>
<% if current_user %>
<tr><td style="border:0"><%= link_to image_tag("settings.png"), edit_user_path(current_user.id) %></td></tr>
<% end %>
</tbody>
</table>
</div>
<% end %>
  <div class="container">
      <div class="content">
        <div class="page-header">
        </div>
        <div class="row">
          <div class="span12">
<%= yield %>
          </div>
        </div>
        <footer>
        copyright © Napster
        </footer>
      </div>
    </div>

<script type="text/javascript">
$(document).ready(function(){
  $(".checkbox_ptaki").iphoneStyle();
  $(".checkbox_kolka").iphoneStyle();
  $(".checkbox_samochod").iphoneStyle();
  $(".checkbox_szesciany").iphoneStyle();
  $(".checkbox_woda").iphoneStyle();
});
$("#password").pwdstr("#password_time");
$("#user_password").pwdstr("#password_time");
</script>
<script>
$(".notice_link").hover(function () {
$('.notice_link').popover('show');
},
function (){
$('.notice_link').popover('hide');
});

setInterval(function() {
if($('.checkbox_ptaki').is(":checked")){
$('.checkbox_ptaki').prop('checked', true).iphoneStyle("refresh");
$('.ptaki_text_field').val('1');
$('.checkbox_kolka').prop('checked', false).iphoneStyle("refresh");
$('.kolka_text_field').val('0');
$('.checkbox_samochod').prop('checked', false).iphoneStyle("refresh");
$('.samochod_text_field').val('0');
$('.checkbox_szesciany').prop('checked', false).iphoneStyle("refresh");
$('.szesciany_text_field').val('0');
$('.checkbox_woda').prop('checked', false).iphoneStyle("refresh");
$('.woda_text_field').val('0');
}
else{
$('.checkbox_ptaki').prop('checked', false).iphoneStyle("refresh");
$('.ptaki_text_field').val('0');
}
if($('.checkbox_kolka').is(":checked")){
$('.checkbox_kolka').prop('checked', true).iphoneStyle("refresh");
$('.kolka_text_field').val('1');
        $('.checkbox_ptaki').prop('checked', false).iphoneStyle("refresh");
$('.ptaki_text_field').val('0');
$('.checkbox_samochod').prop('checked', false).iphoneStyle("refresh");
$('.samochod_text_field').val('0');
$('.checkbox_szesciany').prop('checked', false).iphoneStyle("refresh");
$('.szesciany_text_field').val('0');
$('.checkbox_woda').prop('checked', false).iphoneStyle("refresh");
$('.woda_text_field').val('0');
}
else{
$('.checkbox_kolka').prop('checked', false).iphoneStyle("refresh");
$('.kolka_text_field').val('0');
}
if($('.checkbox_samochod').is(":checked")){
$('.checkbox_samochod').prop('checked', true).iphoneStyle("refresh");
$('.samochod_text_field').val('1');
$('.checkbox_ptaki').prop('checked', false).iphoneStyle("refresh");
$('.ptaki_text_field').val('0');
$('.checkbox_kolka').prop('checked', false).iphoneStyle("refresh");
$('.kolka_text_field').val('0');
$('.checkbox_szesciany').prop('checked', false).iphoneStyle("refresh");
$('.szesciany_text_field').val('0');
$('.checkbox_woda').prop('checked', false).iphoneStyle("refresh");
$('.woda_text_field').val('0');
}
else{
$('.checkbox_samochod').prop('checked', false).iphoneStyle("refresh");
$('.samochod_text_field').val('0');
}
if($('.checkbox_szesciany').is(":checked")){
$('.checkbox_szesciany').prop('checked', true).iphoneStyle("refresh");
$('.szesciany_text_field').val('1');
$('.checkbox_ptaki').prop('checked', false).iphoneStyle("refresh");
$('.ptaki_text_field').val('0');
$('.checkbox_kolka').prop('checked', false).iphoneStyle("refresh");
$('.kolka_text_field').val('0');
$('.checkbox_samochod').prop('checked', false).iphoneStyle("refresh");
$('.samochod_text_field').val('0');
$('.checkbox_woda').prop('checked', false).iphoneStyle("refresh");
$('.woda_text_field').val('0');
}
else{
$('.checkbox_szesciany').prop('checked', false).iphoneStyle("refresh");
$('.szesciany_text_field').val('0');
}
if($('.checkbox_woda').is(":checked")){
$('.checkbox_woda').prop('checked', true).iphoneStyle("refresh");
$('.woda_text_field').val('1');
$('.checkbox_ptaki').prop('checked', false).iphoneStyle("refresh");
$('.ptaki_text_field').val('0');
$('.checkbox_kolka').prop('checked', false).iphoneStyle("refresh");
$('.kolka_text_field').val('0');
$('.checkbox_samochod').prop('checked', false).iphoneStyle("refresh");
$('.samochod_text_field').val('0');
$('.checkbox_szesciany').prop('checked', false).iphoneStyle("refresh");
$('.szesciany_text_field').val('0');
}
else{
$('.checkbox_woda').prop('checked', false).iphoneStyle("refresh");
$('.woda_text_field').val('0');
}
        return
      }, 1500);

 $('div#activity_show').click(function () {
 $( this ).hide("slow");
 $('#show').css("color","#888888");
 });
 $('#show').click(function () {
 $('div#activity_show').show(500);
 $('#show').css("color","#D8D8D8");
 });
 $('.ukryj').click(function () {
 $('.menu_person').animate({"margin-left": "-=85px"}, "slow");
 $('.ukryj').hide("slow");
 $('.pokaz').show(500);
 });
 $('.pokaz').click(function () {
 $('.menu_person').animate({"margin-left": "+=85px"}, "slow");
 $('.ukryj').show(500);
 $('.pokaz').hide("slow");
 });
 $(document).ready(function () {
  if($('.checkbox_avatar').is(":checked")) {
    $('.avatarfromurl').show(500);
  }
 });
 $('.checkbox_avatar').change(function(){
    if($(this).is(":checked")) {
    $('.avatarfromurl').show(500);
    }
    else {
    $('.avatar_text_field').val('');
    $('.avatarfromurl').hide("slow");
   }
});
</script>
</body>
</html>